INSERT INTO users (
    id,
    name,
    username,
    email,
    password_hash,
    university,
    bio,
    role,
    level,
    skill_level,
    skillex_score,
    sessions_completed,
    rating,
    is_active,
    is_online,
    connections_public,
    created_at,
    updated_at,
    joined_at
) VALUES (
    UUID(),
    'Admin User',
    'admin',
    'admin@skillex.app',
    '$2a$10$X3WFPH9USSfOGMktKKVKLeX8LRQc8tSPYk3XTx3CFuM/FwW5z/0ay',
    'SkiilEX HQ',
    'Platform administrator and community manager.',
    'ADMIN',
    'MASTER',
    'EXPERT',
    1500,
    30,
    5.00,
    TRUE,
    TRUE,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON DUPLICATE KEY UPDATE
    role = 'ADMIN',
    password_hash = VALUES(password_hash),
    level = 'MASTER',
    skill_level = 'EXPERT',
    skillex_score = GREATEST(skillex_score, VALUES(skillex_score)),
    sessions_completed = GREATEST(sessions_completed, VALUES(sessions_completed)),
    rating = GREATEST(rating, VALUES(rating)),
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;
