ALTER TABLE users
    ADD COLUMN IF NOT EXISTS github_url VARCHAR(600) NULL,
    ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(600) NULL,
    ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(600) NULL,
    ADD COLUMN IF NOT EXISTS website_url VARCHAR(600) NULL,
    ADD COLUMN IF NOT EXISTS resume_url VARCHAR(600) NULL;
