CREATE TABLE resume_profiles (
    id VARCHAR(36) PRIMARY KEY COLLATE utf8mb4_unicode_ci,
    user_id VARCHAR(36) NOT NULL COLLATE utf8mb4_unicode_ci,
    resume_url VARCHAR(600) NULL,
    source_filename VARCHAR(255) NULL,
    content_type VARCHAR(120) NULL,
    extraction_method VARCHAR(40) NOT NULL DEFAULT 'PDF_TEXT',
    status VARCHAR(30) NOT NULL DEFAULT 'READY',
    raw_text LONGTEXT NULL,
    headline VARCHAR(180) NULL,
    education_summary TEXT NULL,
    experience_summary TEXT NULL,
    project_summary TEXT NULL,
    certification_summary TEXT NULL,
    tools_summary TEXT NULL,
    language_summary TEXT NULL,
    career_goal TEXT NULL,
    teach_summary TEXT NULL,
    learn_summary TEXT NULL,
    suggested_offered_skills_json LONGTEXT NULL,
    suggested_wanted_skills_json LONGTEXT NULL,
    profile_signals_json LONGTEXT NULL,
    confidence INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_resume_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_resume_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_resume_profiles_user (user_id),
    INDEX idx_resume_profiles_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
