package com.skillex.dto.ai;

import java.util.List;

/**
 * DTO for quiz questions generated by the tutor bot.
 * Used for quiz interactions and tracking.
 */
public record TutorQuizQuestionDto(
    /** Unique question identifier */
    String id,

    /** The question text */
    String question,

    /** Type of question: 'multiple-choice', 'short-answer', 'true-false' */
    String questionType,

    /** For multiple choice: list of options */
    List<String> options,

    /** Index of the correct answer (0-based) */
    Integer correctAnswerIndex,

    /** Skill this question is about */
    String skillId,

    /** Skill name for display */
    String skillName,

    /** Difficulty level: 'easy', 'medium', 'hard' */
    String difficulty,

    /** User's answer (if provided) */
    String userAnswer,

    /** User's selected option index (if multiple choice) */
    Integer userAnswerIndex,

    /** Whether the question has been answered */
    Boolean answered,

    /** Whether the answer was correct (if answered) */
    Boolean isCorrect,

    /** Explanation of the correct answer */
    String explanation,

    /** Related session notes for context */
    List<String> relatedSessionNotes
) {}
